In [4]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [5]:
def sigmoid_(x):
    """devuelve el valor de la función sigmoid y su derivada"""
    y = 1.0/(1.0+np.exp(-x))
    der = y*(1-y)
    return y, der
    
def relu_(x):
    """devuleve el valor de la función ReLu y su derivada"""
    y = np.maximum(0,x)
    der = x.copy()
    der[x<=0] = 0
    der[x>0] = 1
    return y, der

def rms_(x,y):
    """calcula el error cuadrático medio"""
    res = (x-y)**2
    return res.mean()

In [93]:
class MLP():
    """crea un objeto para una red neuronal"""
    def __init__(self, red, N, epochs):
        """se inicializan los valores necesarios para la red"""
        self.red = red
        self.lr = lr
#         self.X = X #tamaño Nxn0 (número de datos x dimensión de la red de entrada)
#         self.Y = Y #tamaño NxnL (número de datos x dimensión de la red de salida)
        self.N = N #número de datos de entrada
        self.epochs = epochs
        
        
    def create_(self):
        """crea las matrices w y b iniciales de la red"""
    
        w_list = [0]
        b_list = [0]
        
        for i,j in enumerate(self.red[:-1]):
            w = np.random.randn(j,self.red[i+1])
            b = np.random.randn(1,self.red[i+1])
            w_list.append(w)
            b_list.append(b)
            
        return w_list, b_list
            

    def forward_(self,w_list, b_list, X):
        """hace la multiplicación hacia adelante"""
        z_list = []
        a_list = []
        
        z_list.append(0)  ## este es un dato dummy, solo para el el tamaño de la lista de z y de a coincidan
        a_list.append(X)
        z = np.dot(X,w_list[1])+b_list[1]
        a = sigmoid_(z)[1]
        z_list.append(z); a_list.append(a)
        
        for i in range(len(w_list))[2:]:
            
            z = np.dot(a,w_list[i])+b_list[i]
            a = sigmoid_(z)[0]
            
            z_list.append(z); a_list.append(a)
            
        return z_list, a_list
    
    def backward_(self, z_list, a_list, w_list, b_list, Y):
        """hace la propagación hacia atrás"""
        z_list = z_list
        a_list = a_list
        deltas_list = []
        grad_list = [0]
        grad_b_list = [0]
        inx_red = zip(reversed(range(1,len(self.red))),reversed(self.red[1:]))
        for i,j in inx_red:
            if i == len(self.red)-1:
                delta = 2*(a_list[i]-Y)*sigmoid_(Y)[1]/Y.shape[0]

                deltas_list.insert(0,delta)

            else:
                delta1 = np.zeros((Y.shape[0],j))
                for k in range(Y.shape[0]):
                    for beta in range(j):
                        for alpha in range(self.red[i+1]):
        
                            delta1[k,beta] = deltas_list[0][k,alpha]*w_list[i+1][beta,alpha]*sigmoid_(z_list[i][k,beta])[1]
                deltas_list.insert(0,delta1)
        

        for i in range(len(deltas_list)):
            grad = a_list[i].T@deltas_list[i]
            grad_list.append(grad)
            grad_b = deltas_list[i].sum(0)
            grad_b_list.append(grad_b.reshape(1,len(deltas_list[i][1]))) ## hace un reshape para que coincida la dimensión con los valores de b
        return grad_list, grad_b_list
    
    def loss_(self, a, Y):
        """calcula el error"""
        loss = (a-Y)**2
        return loss.mean()
    
    def slices_(self,X,Y):
            """divide la matriz de entrada y de salida de acuerdo al número de épocas"""
            slices = math.ceil(self.N / epochs)
#             print(slices, epochs)
            X_list = []
            Y_list = []
            for i in range(epochs-1):
#                 print(i, 'a')
                X_s = X[i*slices:(i+1)*slices,:]
                Y_s = Y[i*slices:(i+1)*slices,:]
                X_list.append(X_s)
                Y_list.append(Y_s)
#             print(i, 'b')
            X_s = X[(epochs-1)*slices:,:]
            Y_s = Y[(epochs-1)*slices:,:]
            X_list.append(X_s)
            Y_list.append(Y_s)
                    
            return X_list, Y_list
        
                
            


In [102]:


epochs = 100
lr = 0.01
N = 10000
red = [2,3,5,6,3]

X = np.random.randn(N,red[0])
Y = np.random.randn(N,red[-1])

nn = MLP(red, N, epochs)

w, b = nn.create_()

X_list, Y_list= nn.slices_(X,Y)

# z,a = nn.forward_(w,b,X_list[0])

# gw, gb = nn.backward_(z,a,w,b,Y_list[0])

# for i in range(len(gw))[1:]:
#     print(gw[i].shape, gb[i].shape)
    
def train_(w,b, epochs = epochs, lr=lr):
    """entrena el modelo"""
    for i in range(epochs):
        z,a = nn.forward_(w,b,X_list[i])
        gw, gb = nn.backward_(z,a,w,b,Y_list[i])
        
        for j in range(len(w)):
            w[j] -= lr*gw[j]
            b[j] -= lr*gb[j]
            
        loss = nn.loss_(a[-1],Y_list[i])
        
        print('epoch:', i, 'loss:', loss)
        
train_(w,b)
        
# z, a = prueba.forward_(w,b)
# gr, gr_b= prueba.backward_(z,a,w,b)
# loss = prueba.loss_(a[4])

# for i in range(len(gr))[1:]:
#     print(gr[i].shape, gr_b[i].shape)
# print(loss)
# print(len(prueba1),len(prueba2))


epoch: 0 loss: 1.2992119195650007
epoch: 1 loss: 1.2228137877493808
epoch: 2 loss: 1.5036431789311635
epoch: 3 loss: 1.399909069835776
epoch: 4 loss: 1.6094902459089262
epoch: 5 loss: 1.5383323157962476
epoch: 6 loss: 1.1921649988888594
epoch: 7 loss: 1.1807304381028303
epoch: 8 loss: 1.2171125006983876
epoch: 9 loss: 1.2938921234140102
epoch: 10 loss: 1.417414014649456
epoch: 11 loss: 1.4698451960960317
epoch: 12 loss: 1.3403781361758835
epoch: 13 loss: 1.3838806686611371
epoch: 14 loss: 1.259867181342462
epoch: 15 loss: 1.4499410336879093
epoch: 16 loss: 1.3731862884103434
epoch: 17 loss: 1.566908233415475
epoch: 18 loss: 1.2261302670841685
epoch: 19 loss: 1.34350100915335
epoch: 20 loss: 1.4559696819928087
epoch: 21 loss: 1.2839207559838122
epoch: 22 loss: 1.2717581282366044
epoch: 23 loss: 1.4312967486723276
epoch: 24 loss: 1.5266110987098709
epoch: 25 loss: 1.3942639601580913
epoch: 26 loss: 1.4386164833186277
epoch: 27 loss: 1.3706733194291087
epoch: 28 loss: 1.4831075207404274
e

In [55]:
a = np.array([[1,2,3],[4,5,6]])
print(a**2)

[[ 1  4  9]
 [16 25 36]]


In [281]:
x[:-1]

array([1, 2, 3])

In [56]:
# for i in range(5):
#     print(i)
for i in range(5,0,-1):
    print(i)

5
4
3
2
1


In [102]:
a = [1,2,3,4]
b = [0,1,2,3]
c = zip(a,b)
print(c)


for i,j in c:
    print(i,j)
# print(a)

# for i in a:
#     print(i)
# for i,j in enumerate(reversed(a[1:])):
#     print(i,j)

1 0
2 1
3 2
4 3


In [105]:
for i in range(2,5,1):
    print(i)
for i in range(5):
    print(i)

2
3
4
0
1
2
3
4


In [9]:
a = [1,2,3,4,5]
a[0:30]
print(a[0:3])
# for i in reversed(a[1:]):
#     print(i)

[1, 2, 3]


In [92]:
a = np.array([[1,2,3],[4,5,6]])
a.shape[0]

2